package isn_t_this_e_not_i.now_waypoint_core.domain.auth.exception.follow;

public class DuplicateFollowException extends RuntimeException{
    public DuplicateFollowException(String message) {
        super(message);
    }
}
